OnlineShow/Areas/Admin/Controllers/LoginController.cs
using Model.DAO;
using OnlineShow.Areas.Admin.Models;
using OnlineShow.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Common;
namespace OnlineShow.Areas.Admin.Controllers
{
    public class LoginController : Controller
    {
        // GET: Admin/Login
        public ActionResult Index()
        {
          
            return View();
        }
        public ActionResult Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var dao = new UserDAO();
                var result = dao.Login(Encroptor.MD5Hash(model.PassWord), model.UserName,0);
                
                if (result ==1)
                {
                    var user = dao.GetbyID(model.UserName);
                    var session = new UserLogin();
                    session.UserID = user.ID;
                    session.UserName = user.UserName;
                    session.GroupID = user.GroupID;
                    var listCredential = dao.GetListCredentail(model.UserName);
                    Session.Add(CommonConstants.SESSION_CREDENTIALS, listCredential);
                    Session.Add(CommonConstants.USER_SESSION,session);
                    return RedirectToAction("Index","Home");
                }
                else if(result == 0)
                {
                    ModelState.AddModelError("", "Tài khoản không tồn tại.");
                }
                else if (result == -1)
                {
                    ModelState.AddModelError("", "Tài khoản  bị khóa. ");
                }
                else if( result ==-2)
                {
                    ModelState.AddModelError("", "Mật khẩu không đúng.");
                }
                else if (result == -3)
                {
                    ModelState.AddModelError("", "Tài khoản ko được cấp quyền");
                }
                else
                {
                    ModelState.AddModelError("", "Đăng nhâp thất bại.");

                }
            }
            return View("Index");
        }
        [HttpGet]
        public ActionResult Logout()
        {
            Session[CommonConstants.USER_SESSION] = null;
            return Redirect("/admin/login");
        }
    }
}

OnlineShow/Controllers/UserController.cs
using BotDetect.Web.Mvc;
using Model.DAO;
using Model.EF;
using OnlineShow.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShow.Common;
using Facebook;
using System.Configuration;
using System.Xml.Linq;
using Common;
namespace OnlineShow.Controllers

{
    public class UserController : Controller
    {

        private Uri RedirectUri
        {
            get
            {
                var uriBuilder = new UriBuilder(Request.Url);
                uriBuilder.Query = null;
                uriBuilder.Fragment = null;
                uriBuilder.Path = Url.Action("FacebookCallback");
                return uriBuilder.Uri;
            }
        }
        // GET: User
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Login()

        {
            return View();
        }
        [HttpGet]
        public ActionResult Logout()
        {
            Session[CommonConstants.USER_SESSION] = null;
            return Redirect("/");
        }
        public ActionResult LoginFacebook()
        {
            var fb = new FacebookClient();
            var loginUrl = fb.GetLoginUrl(new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                response_type = "code",
                scope = "email"
            });
            return Redirect(loginUrl.AbsoluteUri);
        }
        public ActionResult FacebookCallback(string code)
        {
            var fb = new FacebookClient();
            dynamic result = fb.Post("oauth/access_token", new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                code = code
            });
            var accessToken = result.access_token;
            if (!string.IsNullOrEmpty(accessToken))
            {
                fb.AccessToken = accessToken;
                // Get  the  user 's  information ,like  email,
                dynamic me = fb.Get("me?fields=first_name,middle_name,last_name,id,email");
                string email = me.email;
                string userName = me.email;
                string firstname = me.first_name;
                string middle_name = me.middle_name;
                string last_name = me.last_name;
                var user = new User();
                user.UserName = userName;
                user.Email = email;
                user.GroupID = CommonConstants.MEMBER_GROUP;
                user.Status = true;
                user.Name = firstname + " " + middle_name + " " + last_name;
                user.CreateDate = DateTime.Now;
                var resultInsert = new UserDAO().InsertForFacebook(user);
                if (resultInsert > 0)
                {
                    var session = new UserLogin();
                    session.UserID = user.ID;
                    session.UserName = user.UserName;
                    session.GroupID = user.GroupID;
                    Session.Add(CommonConstants.USER_SESSION, session);

                }
            }
            return Redirect("/");
        }
        [HttpPost]
        public ActionResult Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var dao = new UserDAO();
                var result = dao.Login(Encroptor.MD5Hash(model.Password), model.UserName);
                if (result == 1)
                {
                    var user = dao.GetbyID(model.UserName);
                    var session = new UserLogin();
                    session.UserID = user.ID;
                    session.UserName = user.UserName;
                    session.GroupID = user.GroupID;
                    Session.Add(CommonConstants.USER_SESSION, session);
                    return Redirect("/");
                }
                else if (result == 0)
                {
                    ModelState.AddModelError("", "Tài khoản không tồn tại.");
                }
                else if (result == -1)
                {
                    ModelState.AddModelError("", "Tài khoản  bị khóa. ");
                }
                else if (result == -2)
                {
                    ModelState.AddModelError("", "Mật khẩu không đúng.");
                }
                else
                {
                    ModelState.AddModelError("", "Đăng nhâp thất bại.");

                }
            }
            return View(model);
        }
        [HttpPost]
        [CaptchaValidation("CaptchaCode", "registerCapchar", "Mã xác nhận không đúng!")]
        public ActionResult Register(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                var dao = new UserDAO();
                if (dao.CheckUserName(model.UserName))
                {
                    ModelState.AddModelError("", "Tên đăng nhập đã tồn tại");
                }
                else if (dao.CheckEmail(model.Email))
                {
                    ModelState.AddModelError("", "Email đã tồn tại");

                }
                else
                {
                    var user = new User();
                    user.UserName = model.UserName;
                    user.Password = Encroptor.MD5Hash(model.Password);
                    user.GroupID = CommonConstants.MEMBER_GROUP;
                    user.Name = model.Name;
                    user.Phone = model.Phone;
                    if (!string.IsNullOrEmpty(model.ProvinceID))
                    {
                        user.ProvinceID = int.Parse(model.ProvinceID) ;
                    }
                    else if (!string.IsNullOrEmpty(model.DistrictID))
                    {
                        user.DistrictID = int.Parse(model.DistrictID);
                    }
                    user.Email = model.Email;
                    user.Address = model.Address;
                    user.CreateDate = DateTime.Now;
                    // trạng thái kích hoạt ->email xác nhận đăng ký
                    user.Status = true; // = true khi  vào email kcíh hoạt thư xác nhận

                    var result = dao.Insert(user);
                    if (result > 0)
                    {
                        ViewBag.Success = "Đăng ký thành công";
                        model = new RegisterModel();
                    }
                    else
                    {
                        ModelState.AddModelError("", "Đăng ký không thành công.");
                    }
                }
            }
            return View(model);
        }
        public JsonResult LoadProvince()
        {
            var xmlDoc = XDocument.Load(Server.MapPath(@"~\assets\client\data\Provinces_Data.xml"));
            var xElements = xmlDoc.Element("Root").Elements("Item").Where(x => x.Attribute("type").Value == "province");
            var list = new List<ProvinceModel>();
            ProvinceModel province = null;
            foreach (var item in xElements)
            {
                province = new ProvinceModel();
                province.ID = int.Parse(item.Attribute("id").Value);
                province.Name = item.Attribute("value").Value;
                list.Add(province);
            }
            return Json(new
            {
                data = list,
                status = true
            });
        }

        public JsonResult LoadDistrict(int provinceID)
        {
            var xmlDoc = XDocument.Load(Server.MapPath(@"~\assets\client\data\Provinces_Data.xml"));
            var xElement = xmlDoc.Element("Root").Elements("Item")
                .Single(x => x.Attribute("type").Value == "province" && int.Parse(x.Attribute("id").Value) == provinceID);
            var list = new List<DistrictModel>();
            DistrictModel district = null;
            foreach (var item in xElement.Elements("Item").Where(x => x.Attribute("type").Value == "district"))
            {
                district = new DistrictModel();
                district.ID = int.Parse(item.Attribute("id").Value);
                district.Name = item.Attribute("value").Value;
                district.ProvinceID = provinceID;

                list.Add(district);
            }
            return Json(new
            {
                data = list,
                status = true
            });
        }
    }
}

OnlineShow/Views/Shared/Footer.cshtml
@model Model.EF.Footer
    @Html.Raw(Model.Content)

OnlineShow/Views/Shared/HeaderCart.cshtml
@model List<OnlineShow.Models.CarItem>
    @{ 
        var payment = 0;
        foreach (var item in Model)
        { var product = item.Product;
            payment += (int)product.Price.GetValueOrDefault(0) * item.Quantity;
        }

    }
<div class="cart">
    <p>
       Chào mừng đến với website <span>Giỏi hàng :</span><div id="dd" class="wrapper-dropdown-2">
           @Model.Count()  sản phẩm  - @payment.ToString("N0") Đ;
            <ul class="dropdown">
                <li>you have no items in your Shopping cart</li>
            </ul>
        </div>
    </p>
</div>

OnlineShow/Views/Shared/MainMenu.cshtml
@model List<Model.EF.Menu>
<div class="menu">
    <ul>
        @foreach (var item in Model)
        {
            <li><a href="@item.Link" target="@item.Target">@item.Text</a></li>
        }
        <div class="clear"></div>
    </ul>
</div>

OnlineShow/Views/Shared/ProductCategory.cshtml
@model  List<Model.EF.ProductCategory>
    

    <ul>
        <h3>DANH MỤC</h3>
        @foreach (var item in Model.Where(x=>x.ParentID==null))
        {
            var child = Model.Where(x => x.ParentID == item.ID);
            var parentClass = child.Count()>0? "class= dropdown-toggle data-toggle=dropdown":"";
            <li class="dropdown">
             <a href="/san-pham/@item.MetaTitle-@item.ID" @parentClass >@item.Name </a>
                @if (child.Count()>0)
                {
                    <ul class="dropdown-menu">
                        @foreach (var childItem in child)
                        {
                            <li>
                                <a href="/san-pham/@childItem.MetaTitle-@childItem.ID">@childItem.Name</a>
                            </li>
                        }
                       
                    </ul>

                }
            </li>
        }
    </ul>
 

OnlineShow/Views/Shared/TopMenu.cshtml
 @model List<Model.EF.Menu>
    
 <div class="call">
    <p><span>Hổ trợ khách hàng ?</span> số điện thoại <span class="number">0233-731-599</span></span></p>
</div>
<div class="account_desc">
    @{
        var session = (OnlineShow.Common.UserLogin)Session[Common.CommonConstants.USER_SESSION];

    }
    @if (session == null)
    {
        <ul>
            @foreach (var item in Model)
            {
                <li><a href="@item.Link">@item.Text</a></li>
            }
        </ul>

    }
    else
    {
        var result = session.GroupID != Common.CommonConstants.MEMBER_GROUP || session.GroupID ==null;
        <ul>
            <li> Xin chào : @session.UserName</li>
            <li>@Html.ActionLink("thoat","Logout","User")</li>
             @if (result)
             {
                <li>@Html.ActionLink("Trang quản lý", "Login", "Admin")</li>
             }
        </ul>
    }

</div>
<div class="clear"></div>

OnlineShow/Views/Shared/_Layout.cshtml
 <!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    @RenderSection("styleHeader", required: false)
    @Styles.Render("~/bundles/csscore")
    @RenderSection("jsHeader", required: false)
    @Scripts.Render("~/bundles/jscore")
</head>
<body>
    <div class="wrap">
        <div class="header">
            <div class="headertop_desc">
            @{ Html.RenderAction("TopMenu", "Home");}
            </div>
            <div class="header_top">
                <div class="logo">
                    <a href="/" ref="nobody"><img src="/assets/client/images/logo.png" alt="_self" /></a>
                </div>
                 @{ Html.RenderAction("HeaderCart", "Home"); }
                <script type="text/javascript">
			function DropDown(el) {
				this.dd = el;
				this.initEvents();
			}
			DropDown.prototype = {
				initEvents : function() {
					var obj = this;

					obj.dd.on('click', function(event){
						$(this).toggleClass('active');
						event.stopPropagation();
					});
				}
			}

			$(function() {

				var dd = new DropDown( $('#dd') );

				$(document).click(function() {
					// all dropdowns
					$('.wrapper-dropdown-2').removeClass('active');
				});

			});

                </script>
                <div class="clear"></div>
            </div>
            <div class="header_bottom">
               @{Html.RenderAction("MainMenu", "Home");}
                <div class="search_box">
                    <form action="/tim-kiem" method="get">
                        <input type="text" id="txtKeyword" name="keyword" placeholder="Gỏ từ khoá"><input type="submit" value="">
                    </form>
                </div>
                <div class="clear"></div>
            </div>
            @RenderSection("slide",required:false)
           
        </div>
        <div class="main">
            @RenderBody()
         
        </div>
    </div>
    <div class="footer">
    @{ Html.RenderAction("Footer", "Home");}
    </div>
    <script type="text/javascript">
		$(document).ready(function() {
			$().UItoTop({ easingType: 'easeOutQuart' });

		});
    </script>
    <a href="#" id="toTop"><span id="toTopHover"> </span></a>
   @Scripts.Render("~/bundles/base");
    @RenderSection("jsFooter", required: false)
</body>
</html>